import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/Home.module.css';

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Roman to Arabig notation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
      <footer className={styles.footer}>
        <Link href="https://www.linkedin.com/in/andres-caballero-a374271b9/" passHref>
          <span>
            By
            &nbsp;
            <span className={styles.boldLink}>
              Andres Caballero
            </span>
          </span>
        </Link>
        <Link href="/informations" passHref>
          <span className={styles.simpleLink}>
            read more
          </span>
        </Link>
      </footer>
    </>
  );
}
